### ISSUE TITLE
Error installing (strict mode conflicts)

### ISSUE THREAD

**Issue by hyfen** [ivanvanderbyl/ember-cli-d3-primitive#3]
I get this error:

```
$ ember install ember-cli-d3-primitive

version: 1.13.8
Installed packages for tooling via npm.
./node_modules/ember-cli-d3-primitive/index.js:9
const concat = require('broccoli-concat');
^^^^^
Use of const in strict mode.
./node_modules/ember-cli-d3-primitive/index.js:9
const concat = require('broccoli-concat');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Function.Addon.lookup (./node_modules/ember-cli/lib/models/addon.js:719:19)
    at ./node_modules/ember-cli/lib/models/addons-factory.js:47:36
    at visit (./node_modules/ember-cli/lib/utilities/DAG.js:23:3)

$ ember -v
version: 1.13.8
node: 0.12.7
npm: 2.13.4
os: darwin x64

```

Any suggestions on how to add to my ember app?

**Comment by ivanvanderbyl** [comment]
Pretty certain this is fixed now. Let me know if `ember install ember-cli-d3-shape` works for you.

**Comment by hyfen** [comment]
Still getting an error from https://github.com/ivanvanderbyl/ember-cli-d3-shape/blob/master/index.js#L111

```
$ ember install ember-cli-d3-shape
./node_modules/ember-cli-d3-shape/index.js:111
      let importFileBaseName = path.parse(require.resolve(packageName)).name;
      ^^^
Unexpected strict mode reserved word
./node_modules/ember-cli-d3-shape/index.js:111
      let importFileBaseName = path.parse(require.resolve(packageName)).name;
      ^^^
SyntaxError: Unexpected strict mode reserved word
```

**Comment by ivanvanderbyl** [comment]
Okay I see whats happening. I'll remove the reference to `let` etc. If you can, upgrade to Node 4+, it supports more of the ES2015 features natively.

**Comment by ivanvanderbyl** [comment]
Release `0.7.1` which should work for you on node 0.12.

**Comment by hyfen** [comment]
Yep, that worked. Thanks!
